;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        beginning-of-buffer
        clipboard-yank
        comint-previous-input
        dabbrev-expand
        delete-horizontal-space
        delete-indentation
        down-list
        ignore
        kill-rectangle
        kill-region
        nxml-electric-slash
        open-next-line
        overwrite-mode
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        python-indent-shift-left
        rope-code-assist
        skeleton-pair-insert-maybe
        toggle-input-method
        yas/expand
        ))

(setq mc/cmds-to-run-once
      '(
        calc-dispatch
        end-of-buffer
        ensime-mouse-motion
        ido-find-file
        ido-insert-file
        ido-switch-buffer
        magit-status
        mark-page
        mark-sexp
        mouse-save-then-kill
        nosetests-all
        view-emacs-news
        ))
